#ifndef GAME_SERVER_ROLE_H
#define GAME_SERVER_ROLE_H

enum
{
    START_HUMANROLE=0,
    PLAYERROLE_GUNTEE,
    END_HUMANROLE,

    START_ZOMBIEROLE,
    PLAYERROLE_SMOKER,
    END_ZOMBIEROLE,

    NUM_PLAYERROLE,
    NUM_HUMANROLE = END_HUMANROLE - START_HUMANROLE - 1,
    NUM_ZOMBIEROLE = END_ZOMBIEROLE - START_ZOMBIEROLE - 1,
};


#endif